name: stream_feed_flutter_workspace
repository: https://github.com/GetStream/stream-feeds-flutter

versioning:
  mode: independent

packages:
  - docs
  - sample_app
  - packages/*
  - packages/*/example

command:
  bootstrap:
    # Dart and Flutter environment used in the project.
    environment:
      sdk: ^3.6.2
      flutter: ">=3.27.4"

    # List of all the dependencies used in the project.
    dependencies:
      auto_route: ^10.0.0
      collection: ^1.18.0
      chewie: ^1.11.3
      dio: ^5.9.0
      equatable: ^2.0.5
      flutter_state_notifier: ^1.0.0
      flutter_svg: ^2.2.0
      freezed_annotation: ^3.0.0
      get_it: ^8.0.3
      google_fonts: ^6.3.0
      file_picker: ^8.1.4
      firebase_core: ^3.0.0
      firebase_messaging: ^15.0.0
      flex_grid_view: ^0.1.0
      flutter_local_notifications: ^18.0.1
      http: ^1.1.0
      injectable: ^2.5.1
      intl: ">=0.18.1 <=0.21.0"
      internet_connection_checker_plus: ^2.9.0
      jiffy: ^6.3.2
      photo_view: ^0.15.0
      json_annotation: ^4.9.0
      meta: ^1.9.1
      retrofit: ^4.6.0
      rxdart: ^0.28.0
      shared_preferences: ^2.5.3
      state_notifier: ^1.0.0
      stream_feeds: ^0.2.0
      stream_core: ^0.2.0
      video_player: ^2.10.0
      uuid: ^4.5.1

    # List of all the dev_dependencies used in the project.
    dev_dependencies:
      auto_route_generator: ^10.0.0
      build_runner: ^2.4.15
      flutter_launcher_icons: ^0.14.4
      freezed: ^3.0.0
      injectable_generator: ^2.7.0
      json_serializable: ^6.9.5
      mocktail: ^1.0.4
      retrofit_generator: ^9.6.0
      test: ^1.26.3

scripts:
  postclean:
    run: melos run clean:flutter --no-select
    description: Runs "flutter clean" in all Flutter packages

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks

  analyze:all:
    run: melos run analyze && melos run metrics
    description: Run all

  analyze:
    run: |
      melos exec -c 5 --ignore="*example*" -- \
        dart analyze --fatal-infos .
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  analyze:warning:
    run: |
      melos exec -c 5 --ignore="*example*" -- \
        dart analyze --fatal-warnings .
    description: |
      Run `dart analyze` in all packages.
       Flags all compiler `errors` in the project.

  analyze:error:
    run: |
      melos exec -c 5 --ignore="*example*" -- \
        dart analyze --no-fatal-warnings .
    description: |
      Run `dart analyze` in all packages.
       Flags all compiler `errors` in the project.

  format:
    run: dart format .
    description: |
      Run `dart format .` in all packages.

  format:verify:
    run: dart format --set-exit-if-changed .
    description: |
      Run `dart format --set-exit-if-changed .` in all packages.

  metrics:
    run: |
      melos exec -c 1 --ignore="*example*" -- \
        flutter pub run dart_code_metrics:metrics analyze lib
    description: |
      Run `dart_code_metrics` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  lint:pub:
    run: |
      melos exec -c 5 --no-private --ignore="*example*" -- \
            flutter pub publish --dry-run
    description: |
      Run `pub publish --dry-run` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  generate:all:
    run: melos run generate:dart && melos run generate:flutter
    description: Build all generated files for Dart & Flutter packages in this project.

  generate:dart:
    run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Dart packages in this project.

  generate:flutter:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.

  gen-l10n: >
    melos exec -c 1 --fail-fast --depends-on=flutter_localizations -- \
     "flutter gen-l10n && dart format ."

  test:all:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "flutter test --coverage"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 4 --fail-fast -- "flutter test --coverage"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test

  test:fixes:
    run: melos exec -c 4 --fail-fast -- "cd test_fixes && dart fix --compare-to-golden"
    description: Verify dart fixes for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test_fixes

  update:goldens:
    run: melos exec -c 1 --depends-on="alchemist" -- "flutter test --tags golden --update-goldens"
    description: Update golden files for all packages in this project.

  clean:flutter:
    run: melos exec -c 4 --fail-fast -- "flutter clean"
    description: Run Flutter clean for a specific package in this project.
    packageFilters:
      flutter: true

  coverage:ignore-file:
    run: |
      melos exec -c 5 --fail-fast -- "\$MELOS_ROOT_PATH/.github/workflows/scripts/remove-from-coverage.sh"
    description: Removes all the ignored files from the coverage report.
    packageFilters:
      dirExists: coverage

  docs:
    run: |
      npm install -g https://github.com/GetStream/stream-chat-docusaurus-cli &&
      npx stream-chat-docusaurus -i -s
    description: Runs the docusaurus documentation locally.

  gen:feeds:
    run: $MELOS_ROOT_PATH/scripts/generate.sh
    description: Generate Feeds Dart client from Chat OpenAPI
