include: ../analysis_options.yaml

analyzer:
  # TODO: not working if added on the root analysis file
  exclude:
    # exclude all the generated files
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    cascade_invocations: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false