name: sample_app
description: "A demo app for the Stream Feeds SDK"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  auto_route: ^10.0.0
  chewie: ^1.11.3
  collection: ^1.18.0
  file_picker: ^8.1.4
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flex_grid_view: ^0.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_state_notifier: ^1.0.0
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_fonts: ^6.3.0
  injectable: ^2.5.1
  internet_connection_checker_plus: ^2.9.0
  jiffy: ^6.3.2
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  stream_feeds: ^0.3.1
  video_player: ^2.10.0

dev_dependencies:
  auto_route_generator: ^10.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/