name: sample_app
description: "A demo app for the Stream Feeds SDK"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  auto_route: ^10.0.0
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  file_picker: ^8.1.4
  flex_color_scheme: ^8.1.1
  flex_grid_view: ^0.1.0
  flutter:
    sdk: flutter
  flutter_state_notifier: ^1.0.0
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  google_fonts: ^6.3.0
  injectable: ^2.5.1
  jiffy: ^6.3.2
  shared_preferences: ^2.5.3
  stream_feeds:
    path: ../packages/stream_feeds

dev_dependencies:
  auto_route_generator: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/