name: pana

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stream_feed:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
      - name: 📊 Verify Pana Score
        uses: ./.github/actions/pana
        with:
          working_directory: packages/stream_feed
          min_score: 130  # Missing 10 points for no example and 10 points for license
