name: 'PR is Conventional and Semantic'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conventional_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        with: 
          scopes: |
            llc
            repo
            samples
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semantic_changelog_update:
    needs: conventional_pr_title # Trigger after the [conventional_pr_title] completes
    runs-on: ubuntu-latest
    steps:
      - uses: GetStream/verify-semantic-changelog-update@main
        with:
          scopes: |
            {
              "llc": "packages/stream_feed"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}